### PR TITLE
Workflow

### PR DESCRIPTION
**Pull request by mltrev23**
## Summary by Sourcery

Introduce a new translation module with comprehensive support for various translation tasks, including text-to-text, text-to-speech, speech-to-text, and speech-to-speech. Enhance the validator with asynchronous processing and improved reward systems. Implement a FastAPI application for serving function documentation and executing functions dynamically. Add build configurations and scripts for setting up the translation module and ensure code style compliance with flake8.

New Features:
- Introduce a new translation module with support for text-to-text, text-to-speech, speech-to-text, and speech-to-speech tasks using a new Translation class.
- Add a FastAPI application for serving Python function documentation and executing functions dynamically.
- Implement a new API for managing and processing translation requests using FastAPI and Pydantic models.

Enhancements:
- Refactor the validator to support asynchronous processing and serialization of translation requests.
- Improve the reward system by introducing separate functions for text and speech rewards, utilizing cosine similarity, BLEU score, and Levenshtein similarity for text, and MFCC features for speech.

Build:
- Add a setup.cfg file to configure flake8 for code style checks.
- Include a new install script for the translation module, setting up dependencies and cloning necessary repositories.

Documentation:
- Generate and serve markdown documentation for Python functions using FastAPI and markdown2.

Chores:
- Add a data directory with salts.json and functions.json for storing configuration and function metadata.

### CODE REVIEW

**Comment by jzanecook** [comment]
@mltrev23 Could you give a little more guidance for the .env configuration? I would like to QA locally but I'm not entirely sure what to put, here's my breakdown.
```
BT_NETWORK= # testnet?
BT_NETUID= # In testnet, whatever besides 0?
BT_AXON_MINER_PORT= # Anything?
BT_AXON_MINER_IP= # 0.0.0.0?
BT_AXON_MINER_EXTERNAL_PORT= # Anything?
BT_AXON_MINER_EXTERNAL_IP= # 0.0.0.0?
BT_AXON_VALIDATOR_PORT= # Anything?
BT_AXON_VALIDATOR_IP= # 0.0.0.0?
BT_AXON_VALIDATOR_EXTERNAL_PORT= # Anything?
BT_AXON_VALIDATOR_EXTERNAL_IP= # 0.0.0.0?
BT_AXON_MAX_WORERS= # Worers?
BT_MINER_COLDKEY= # Whatever my key's name is
BT_MINER_HOTKEY= # Whatever my key's name is
BT_VALIDATOR_COLDKEY= # Whatever my key's name is
BT_VALIDATOR_HOTKEY= # Whatever my key's name is
BT_WALLET_PATH= # ~/.bittensor/wallets or whatever it was
INFERENCE_URL= # ?? OpenAI?
INFERENCE_API_KEY= # ?? Can I point to my ollama? I don't use OpenAI personally
```

**Comment by mltrev23** [comment]
BT_NETWORK="test"
BT_NETUID=197
BT_AXON_MINER_PORT=9998
BT_AXON_MINER_IP="0.0.0.0"
BT_AXON_MINER_EXTERNAL_PORT=9998
BT_AXON_MINER_EXTERNAL_IP="198.53.168.98"
BT_AXON_VALIDATOR_PORT=9997
BT_AXON_VALIDATOR_IP="0.0.0.0"
BT_AXON_VALIDATOR_EXTERNAL_PORT=9997
BT_AXON_VALIDATOR_EXTERNAL_IP="198.53.168.98"
BT_AXON_MAX_WORERS=5
BT_MINER_COLDKEY="sylliba"
BT_MINER_HOTKEY="miner1"
BT_VALIDATOR_COLDKEY="sylliba"
BT_VALIDATOR_HOTKEY="validator1"
BT_WALLET_PATH="~/.bittensor/wallets"
INFERENCE_URL="https://api.openai.com/v1/chat/completions"
INFERENCE_API_KEY="sk-proj-wbxleKS1FVyzmnjVAlZtT3BlbkFJW2SjN3e9woQzISy1amUa"

**Comment by mltrev23** [comment]
this is my env variable, you can change some configs to align with yours

**Comment by coolrazor007** [comment]
When doing step 8 I get the following error.  Here's the command: python3 -m modules.translation.setup_translation

```Building wheels for collected packages: sndfile, ggml-python
  Building wheel for sndfile (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      /home/ubuntu/repos/Sylliba-Subnet/.venv/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/sndfile
      copying sndfile/vio.py -> build/lib.linux-x86_64-cpython-310/sndfile
      copying sndfile/io.py -> build/lib.linux-x86_64-cpython-310/sndfile
      copying sndfile/formats.py -> build/lib.linux-x86_64-cpython-310/sndfile
      copying sndfile/build.py -> build/lib.linux-x86_64-cpython-310/sndfile
      copying sndfile/__init__.py -> build/lib.linux-x86_64-cpython-310/sndfile
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-cpython-310/sndfile._sndfile.c'
      creating build/temp.linux-x86_64-cpython-310
      building 'sndfile._sndfile' extension
      creating build/temp.linux-x86_64-cpython-310/build
      creating build/temp.linux-x86_64-cpython-310/build/temp.linux-x86_64-cpython-310
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/ubuntu/repos/Sylliba-Subnet/.venv/include -I/usr/include/python3.10 -c build/temp.linux-x86_64-cpython-310/sndfile._sndfile.c -o build/temp.linux-x86_64-cpython-310/build/temp.linux-x86_64-cpython-310/sndfile._sndfile.o
      build/temp.linux-x86_64-cpython-310/sndfile._sndfile.c:575:10: fatal error: sndfile.h: No such file or directory
        575 | #include <sndfile.h>
            |          ^~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sndfile
  Running setup.py clean for sndfile
  Building wheel for ggml-python (pyproject.toml) ... done
  Created wheel for ggml-python: filename=ggml_python-0.0.37-cp310-cp310-linux_x86_64.whl size=732442 sha256=8d1c109fb650af0b1da70f6eca80ac47b78b7a882866a09741aa74ddc896eab5
  Stored in directory: /tmp/pip-ephem-wheel-cache-ipz8kyo_/wheels/51/fb/b1/e6c55264998cbc7f093cef3727deac6bc475f672dfc70cc176
Successfully built ggml-python
Failed to build sndfile
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sndfile)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/repos/Sylliba-Subnet/modules/translation/setup_translation.py", line 25, in <module>
    subprocess.run(command, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', 'modules/translation/install_translation.sh']' returned non-zero exit status 1.```

**Comment by coolrazor007** [comment]
Steps:
SKIP step 8
Add step: `sudo apt-get install python3 python3-dev python3-venv python3-pip python-is-python3 libsndfile1-dev libgmp10-dev -y`
Add step: `export PYTHONPATH=.`

**Comment by coolrazor007** [comment]
so what is the LLM being used for?  Just generating a new string to translate with the translation model?

if it is for just generating new "text" for translating every time, then I think we should either use the Phi model (open source 3GB model) for that OR use RSS (link https://en.wikipedia.org/wiki/RSS) and grab something daily

**Pull request merged**
